import Head from "next/head";
import SideNavBar from "../components/static/SideNavBar";
import styles from "../styles/Home.module.css";
import SearchBar from "../components/static/SearchBar";
import Summary from "../components/summary/Summary";
import Questions from "../components/questions/Questions";
import Statistic02 from "../components/charts/Statistic02";
import PastPrediction from "../components/prediction/PastPrediction";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="sm:flex">
        <SideNavBar />
        <div className="w-full">
          <SearchBar />
          <div className="flex">
            <div>
              <Summary />
              <Statistic02 />
              <PastPrediction />
            </div>
            <div>
              <Questions />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
